services:
  # Pulsar settings
  pulsar-standalone:
    image: apachepulsar/pulsar:3.0.7
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"
    volumes:
      - "pulsardata:/pulsar/data"
      - "pulsarconf:/pulsar/conf"
    ports:
      - "6650:6650"
      - "8080:8080"
      - "8081:8081"

  # Redis storage for state persistence
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"

  # Postgres Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "exampleuser"
      POSTGRES_PASSWORD: "examplepass"
      POSTGRES_DB: "exampledb"
    ports:
      - "5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "examplepass"
      MYSQL_DATABASE: "exampledb"
      MYSQL_USER: "exampleuser"
      MYSQL_PASSWORD: "examplepass"
    ports:
      - "3306:3306"
    volumes:
      - "mysqldata:/var/lib/mysql"

volumes:
  pulsardata:
  pulsarconf:
  redisdata:
  postgresdata:
  mysqldata: